dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: n0++htYD4qirGamqlUA+tgNH6IwBEgGveoF6TQaGO71Bo1R3s8FzuYkuF+Q4ZGc2JQh88Ej86jfFvH2jz8tqiNspiCQ1trHmlUJkrtAi7pp2fpKUPOv66Rb9e86KQUQ/+0N30OnYTiX7plcwTcw0n6b+PONtAu8oCEeAlXi4U+7uSxZqKlv3G2j0wpBQJzbWy3EFtKHr6mbCJpZkv346efDD/OqQnu+LMRNUuWKjXEe/uGANvCulQ6fR9o2sh7/TY7vHA7iukOJi6Ypy0rAmdzbzD2NoV9Ev23Ke05PGPSpKXiVMi7UvTnK73mybkwRPo/ZRpYRyfSPnwZbZZ0yvKp/ews5DhF8ZUyH4vz8h7vuaPvjDN4T3lirqbi+aZ69ZOVsQVpyxebC6meKlg9jR7RqA0T7uo6VZWq5GNVcBZhMXg7eLFF0dbLKRuHz/p36OifwvZBNiqlt/1Cu3V5pGy9UEth/BPYeNc5JlXJxTLIm4EO378ZchepPljUjGet71HE5s8kpmxhrmHD/yBu70Ag1f58yilvIc2QojE3df5br+mHWZLVae7zcS8RCNLxjF4CgCh4qggbyJQqYiC+IcmnDOwUDvvX/NA9XL/GJJbO2iWsjeT0DdP+LjNqToeNlVq7aWHJul79+BZW1OeMDSK+qzL5ae8CWf5/zPdtQLYLo=
