version: '3.3'
services:
  post_db:
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    #build: ./ui
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    #build: ./post-py
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    #build: ./comment
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net


  prometheus:
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/prometheus:${PROM_VERSION}
    networks:
      - front_net
      - back_net
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: #additional parameters to cmd
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' #время хранения метрик

  node-exporter:
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - front_net
      - back_net
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'


volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
